name: ADF CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Test compatibility of source dependencies
        run: |
          make clean src_deps
          echo "Source dependencies are compatible!"
      - name: Run tox
        run: |
          make clean tox
      - name: Build fully
        run: |
          make clean build
